#!/usr/bin/env node
// Create an External Order Drop franchise account from the server shell (run as root).
//   node create-account.js --name "Test01" [--username test01] [--branches JC001,JC002]
// Talks to the running jc-round-drop service on loopback, authenticating with a short-lived
// admin token signed by the service's own secret.key (readable only by root/www-data).
// The password is generated by the service and printed once.
'use strict';
const fs = require('fs'), http = require('http'), crypto = require('crypto'), path = require('path');

const DATA_DIR = process.env.DATA_DIR || '/opt/jc-round-drop/data';
const DROP = process.env.DROP_URL || 'http://127.0.0.1:8093';
const JCR = process.env.JCR_API || 'http://127.0.0.1:8092';
const ADMIN_ROLES = ['MAIN ADMIN', 'SCM Manager', 'WH ADMIN', 'PCM ADMIN'];

const args = {};
for (let i = 2; i < process.argv.length; i++) {
  const m = process.argv[i].match(/^--([a-z]+)$/);
  if (m) args[m[1]] = process.argv[++i];
}
if (!args.name) { console.error('usage: create-account.js --name "Shop name" [--username id] [--branches JC001,JC002]'); process.exit(2); }

function req(method, url, body, headers) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const r = http.request(url, { method, headers: { ...(data ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(data) } : {}), ...headers } }, res => {
      let t = ''; res.on('data', c => t += c); res.on('end', () => { try { resolve({ status: res.statusCode, json: JSON.parse(t) }); } catch (_) { resolve({ status: res.statusCode, json: null }); } });
    });
    r.on('error', reject); if (data) r.write(data); r.end();
  });
}

(async () => {
  const secret = fs.readFileSync(path.join(DATA_DIR, 'secret.key'), 'utf8').trim();
  const st = await req('GET', JCR + '/state');
  const admin = ((st.json && st.json.state && st.json.state.users) || []).find(u => u.role === 'MAIN ADMIN' && u.active !== false)
    || ((st.json && st.json.state && st.json.state.users) || []).find(u => ADMIN_ROLES.includes(u.role) && u.active !== false);
  if (!admin) throw new Error('no active admin user found in jc-round state');
  const body = Buffer.from(JSON.stringify({ k: 'adm', uid: admin.id, name: admin.name, exp: Date.now() + 60 * 1000 })).toString('base64url');
  const token = body + '.' + crypto.createHmac('sha256', secret).update(body).digest('base64url');
  const branches = args.branches ? args.branches.split(',').map(s => s.trim()).filter(Boolean) : [];
  const r = await req('POST', DROP + '/admin/accounts', { name: args.name, username: args.username || '', branches }, { Authorization: 'Bearer ' + token });
  if (r.status !== 201) throw new Error((r.json && r.json.error) || 'HTTP ' + r.status);
  console.log('Account created (createdBy: ' + admin.name + ')');
  console.log('  Portal   : ' + (process.env.PUBLIC_ORIGIN || 'https://jc-round.scm-backoffice.com') + '/#/drop');
  console.log('  ID       : ' + r.json.account.username);
  console.log('  Password : ' + r.json.password + '   ← shown once');
  console.log('  Branches : ' + (r.json.account.branches.length ? r.json.account.branches.join(', ') : 'all'));
})().catch(e => { console.error('error: ' + e.message); process.exit(1); });
